name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ current ]


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: |
          node -v
          pnpm i 
      - name: Download objaverse
        run: |
          mkdir obaverse && cd obaverse && wget https://huggingface.co/datasets/allenai/objaverse/resolve/main/object-paths.json.gz
          cd obaverse && wget https://huggingface.co/datasets/allenai/objaverse/resolve/main/glbs/000-020/a948cbd292384d71adaab68ed6438a17.glb

      - name: Build tools web production
        run: pnpm run pro
      - name: Push to Aliyun OSS
        uses: tiyee/aliyun-oss-auto-upload@v2.0.6
        with:
          # aliyun config
          region: ${{ secrets.REGION }} # like oss-cn-beijing
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.BUCKET }}
          secure: false
          # deploy config
          local-folder: html
          remote-dir: /
      - name: Push obaverse to Aliyun OSS
        uses: tiyee/aliyun-oss-auto-upload@v2.0.6
        with:
          # aliyun config
          region: ${{ secrets.REGION }} # like oss-cn-beijing
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.BUCKET }}
          secure: false
          # deploy config
          local-folder: obaverse
          remote-dir: /

